name : CI workflows
on: 
  push:
   branches: ["main"]
  pull_request:
    branches: ["main"]
    # when a push or pull request is performed on main branch
jobs: # job will run on ubuntu lates runner when before defined step is reached
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: | # pip for running multiple lines of code
          python -m pip install --upgrade pip 
          pip install -r requirements.txt    

      - name: Lint with flake8
        run: | # quality check of code
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
      